### PR TITLE
Add check that looks for vulnerable packages

### PR DESCRIPTION
**Pull request by andrew-d**

### CODE REVIEW

**Comment by andrew-d** [comment]
Okay, this looks like it's ready to go!

r? @gphat

**Comment by gphat** [comment]
Can you add some blurbs to the `README` for this? (reviews closer now)

**Comment by gphat** [comment]
👍 

This looks great! I don't do PEP8 checks or whatever. I scanned it and it all looked sane. I assume the input will be a list of names and versions that we keep on all boxes? Can you elaborate a bit on how we'll use it? (Security or someone will update the list, etc?)

**Comment by andrew-d** [comment]
Re-added approval (from above)

**Pull request merged**
