### PR TITLE
Add Veneur check to track deployed version and build age

### PR DESCRIPTION
**Pull request by ChimeraCoder**
Add Veneur check to track deployed version and build age.

r? @cory-stripe 
cc @stripe/observability

### CODE REVIEW

**Comment by cory-stripe** [comment]
I love the idea, but feel the need to ask "what if there's nothing to build for a week?"

Seems this could either be an option to the check or deferred to a monitor that uses the seconds and leaves things done on the monitoring side?

**Comment by ChimeraCoder** [comment]
Oh, two things:

1) We want this to be QA-only, at least for now (that's something we'll handle in our puppet config)

2) We may eventually want this in prod, and we'll want a different max age for that than QA


I was going to implement that by having a config variable for the age, but I guess we can do this in the monitor. I was thinking of this conceptually as a service check, but there's no reason it has to be.

**Comment by cory-stripe** [comment]
👍

**Comment by ChimeraCoder** [comment]
Fixed some stuff. re-r? @cory-stripe 

Oh, and as for "what if there's nothing to build for a week" - our current state of velocity for Veneur is that there's pretty much no time when we're not at least merging a commit to master once each week. The only exception might be the week of Christmas/New Year's, and that's easily solved by muting.


The alternate approach is to do a shallow clone and check the actual most-recent commit and its age from Github, but that poses a lot of logistical problems.

**Comment by cory-stripe** [comment]
👍

**Comment by ChimeraCoder** [comment]
Okay, one last change. Tested this on QA as well. re-r? @cory-stripe

**Comment by cory-stripe** [comment]
👍

**Pull request merged**
