### PR TITLE
Add datadog check for kernel version

### PR DESCRIPTION
**Pull request by carleton-stripe**
Adds a check for reporting the kernel version and default grub entry.  The default grub entry will indicate which kernel will be loaded on reboot. 

r? @cory-stripe

### CODE REVIEW

**Comment by cory-stripe** [comment]
👍 

Seems reasonable! I assume you verified it worked in QA or something?

**Comment by carleton-stripe** [comment]
Woops, thanks for the reminder.  Testing in QA revealed a couple bugs which I sent up a commit to fix.  I have now successfully run this in QA and see the metric reported in Datadog.

r? @cory-stripe

**Comment by cory-stripe** [comment]
👍

**Comment by carleton-stripe** [comment]
The build output indicated success, so I went ahead and merged.

**Pull request merged**
